on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@b4
        with:
          go-version: '1.22.1'
      
      - name: Set up Keys
        uses: kielabokkie/ssh-key-know-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}
      
      - name: Deploy
        run: make deploy